name: Continuous Integration

on:
  push:
    branches:
      - development
      - main

  pull_request:
    branches:
      - development
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v7.0.1

      - name: Set up .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0.x"

      # Restore

      - name: Restore API
        run: dotnet restore api/Amiasea.API.csproj

      - name: Restore Data Migrations
        run: dotnet restore data/Amiasea.Data.Migrations/Amiasea.Data.Migrations.csproj

      - name: Restore Functions
        run: dotnet restore functions/Amiasea.Functions.csproj

      - name: Restore Worker
        run: dotnet restore worker/Amiasea.Worker.csproj

      # Unit tests

      - name: Test API
        run: dotnet test api/Amiasea.API.csproj --no-restore

      - name: Test Data Migrations
        run: dotnet test data/Amiasea.Data.Migrations/Amiasea.Data.Migrations.csproj --no-restore

      - name: Test Functions
        run: dotnet test functions/Amiasea.Functions.csproj --no-restore

      - name: Test Worker
        run: dotnet test worker/Amiasea.Worker.csproj --no-restore